[package]
name = "make_library"
version = "0.1.0"
edition = "2021"

[lib]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "efern"
path = "src/bin/efern.rs"

[dependencies]
